// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.MorseCode
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("text")]
        public string Text { get; set; }

        [JsonProperty("morse")]
        public string Morse { get; set; }

        [JsonProperty("stats")]
        public Stats Stats { get; set; }

        [JsonProperty("valid")]
        public bool Valid { get; set; }

        [JsonProperty("audio")]
        public Audio Audio { get; set; }
    }

    public partial class Audio
    {
        [JsonProperty("audioFile")]
        public string AudioFile { get; set; }

        [JsonProperty("format")]
        public string Format { get; set; }

        [JsonProperty("downloadURL")]
        public Uri DownloadUrl { get; set; }

        [JsonProperty("duration")]
        public string Duration { get; set; }

        [JsonProperty("frequency")]
        public string Frequency { get; set; }

        [JsonProperty("sampleRate")]
        public string SampleRate { get; set; }

        [JsonProperty("expires")]
        public long Expires { get; set; }
    }

    public partial class Stats
    {
        [JsonProperty("characters")]
        public long Characters { get; set; }

        [JsonProperty("dits")]
        public long Dits { get; set; }

        [JsonProperty("dahs")]
        public long Dahs { get; set; }
    }
}
